### ISSUE TITLE
Which versions for pre-training?

### ISSUE THREAD

**Issue by marcelbra** [IntelLabs/academic-budget-bert#14]
First of all: thanks for your work! I am trying to run the pre-training script. I keep having compatbility issues while installing dependencies. I would be interested to know which of these you used:

1. Nvidia driver version
2. Pytorch version + its CUDA version
3. CUDA version
4. CuDNN version
5. Python version
6. OS

**Comment by peteriz** [comment]
Hi @marcelbra, I used python 3.7, pytorch 1.9 with CUDA 11.3
