### ISSUE TITLE
Question: Easiest way to load deepspeed checkpoints as standard PyTorch models?

### ISSUE THREAD

**Issue by QuintinPope** [IntelLabs/academic-budget-bert#16]
Hello,
Thank you for this codebase.

When I try to load a finetune checkpoint with BertLMHeadModel.from_pretrained(model_path), it fails to load the weights on file. I get warnings like:

> Some weights of the model checkpoint at training_out/random_init_large/run_1/pretraining_experiment-/epoch1000000_step63491/ were not used when initializing BertLMHeadModel: ['bert.encoder.FinalLayerNorm.weight', 'bert.encoder.FinalLayerNorm.bias', 'bert.encoder.layer.0.PreAttentionLayerNorm.weight', 'bert.encoder.layer.0.PreAttentionLayerNorm.bias', 'bert.encoder.layer.0.PostAttentionLayerNorm.weight', 'bert.encoder.layer.0.PostAttentionLayerNorm.bias', 'bert.encoder.layer.0.intermediate.dense_act.dense.weight', 'bert.encoder.layer.0.intermediate.dense_act.dense.bias', 'bert.encoder.layer.1.PreAttentionLayerNorm.weight', 'bert.encoder.layer.1.PreAttentionLayerNorm.bias', 'bert.encoder.layer.1.PostAttentionLayerNorm.weight', 'bert.encoder.layer.1.PostAttentionLayerNorm.bias', 'bert.encoder.layer.1.intermediate.dense_act.dense.weight', 'bert.encoder.layer.1.intermediate.dense_act.dense.bias', 'bert.encoder.layer.2.PreAttentionLayerNorm.weight', 'bert.encoder.layer.2.PreAttentionLayerNorm.bias', 'bert.encoder.layer.2.PostAttentionLayerNorm.weight', 'bert.encoder.layer.2.PostAttentionLayerNorm.bias', 'bert.encoder.layer.2.intermediate.dense_act.dense.weight', 'bert.encoder.layer.2.intermediate.dense_act.dense.bias', 'bert.encoder.layer.3.PreAttentionLayerNorm.weight', 'bert.encoder.layer.3.PreAttentionLayerNorm.bias', 'bert.encoder.layer.3.PostAttentionLayerNorm.weight', 'bert.encoder.layer.3.PostAttentionLayerNorm.bias', 'bert.encoder.layer.3.intermediate.dense_act.dense.weight', 'bert.encoder.layer.3.intermediate.dense_act.dense.bias', 'bert.encoder.layer.4.PreAttentionLayerNorm.weight', 'bert.encoder.layer.4.PreAttentionLayerNorm.bias', 'bert.encoder.layer.4.PostAttentionLayerNorm.weight', 'bert.encoder.layer.4.PostAttentionLayerNorm.bias', 'bert.encoder.layer.4.intermediate.dense_act.dense.weight', 'bert.encoder.layer.4.intermediate.dense_act.dense.bias', 'bert.encoder.layer.5.PreAttentionLayerNorm.weight', 'bert.encoder.layer.5.PreAttentionLayerNorm.bias', 'bert.encoder.layer.5.PostAttentionLayerNorm.weight', 'bert.encoder.layer.5.PostAttentionLayerNorm.bias', 'bert.encoder.layer.5.intermediate.dense_act.dense.weight', 'bert.encoder.layer.5.intermediate.dense_act.dense.bias', 'bert.encoder.layer.6.PreAttentionLayerNorm.weight', 'bert.encoder.layer.6.PreAttentionLayerNorm.bias', 'bert.encoder.layer.6.PostAttentionLayerNorm.weight', 'bert.encoder.layer.6.PostAttentionLayerNorm.bias', 'bert.encoder.layer.6.intermediate.dense_act.dense.weight', 'bert.encoder.layer.6.intermediate.dense_act.dense.bias', 'bert.encoder.layer.7.PreAttentionLayerNorm.weight', 'bert.encoder.layer.7.PreAttentionLayerNorm.bias', 'bert.encoder.layer.7.PostAttentionLayerNorm.weight', 'bert.encoder.layer.7.PostAttentionLayerNorm.bias', 'bert.encoder.layer.7.intermediate.dense_act.dense.weight', 'bert.encoder.layer.7.intermediate.dense_act.dense.bias', 'bert.encoder.layer.8.PreAttentionLayerNorm.weight', 'bert.encoder.layer.8.PreAttentionLayerNorm.bias', 'bert.encoder.layer.8.PostAttentionLayerNorm.weight', 'bert.encoder.layer.8.PostAttentionLayerNorm.bias', 'bert.encoder.layer.8.intermediate.dense_act.dense.weight', 'bert.encoder.layer.8.intermediate.dense_act.dense.bias', 'bert.encoder.layer.9.PreAttentionLayerNorm.weight', 'bert.encoder.layer.9.PreAttentionLayerNorm.bias', 'bert.encoder.layer.9.PostAttentionLayerNorm.weight', 'bert.encoder.layer.9.PostAttentionLayerNorm.bias', 'bert.encoder.layer.9.intermediate.dense_act.dense.weight', 'bert.encoder.layer.9.intermediate.dense_act.dense.bias', 'bert.encoder.layer.10.PreAttentionLayerNorm.weight', 'bert.encoder.layer.10.PreAttentionLayerNorm.bias', 'bert.encoder.layer.10.PostAttentionLayerNorm.weight', 'bert.encoder.layer.10.PostAttentionLayerNorm.bias', 'bert.encoder.layer.10.intermediate.dense_act.dense.weight', 'bert.encoder.layer.10.intermediate.dense_act.dense.bias', 'bert.encoder.layer.11.PreAttentionLayerNorm.weight', 'bert.encoder.layer.11.PreAttentionLayerNorm.bias', 'bert.encoder.layer.11.PostAttentionLayerNorm.weight', 'bert.encoder.layer.11.PostAttentionLayerNorm.bias', 'bert.encoder.layer.11.intermediate.dense_act.dense.weight', 'bert.encoder.layer.11.intermediate.dense_act.dense.bias', 'cls.predictions.transform.dense_act.dense.weight', 'cls.predictions.transform.dense_act.dense.bias']
\- This IS expected if you are initializing BertLMHeadModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
\- This IS NOT expected if you are initializing BertLMHeadModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

I'm not familiar with deepspeed and would prefer not to use it in my downstream analysis. Is there a straightforward way to load the finetune checkpoint as a standard PyTorch model?

Thank you for your help!

**Comment by peteriz** [comment]
Hi @QuintinPope, I'm guessing you're trying to load a pre-trained model (or checkpoint) that wasn't trained using `BertLMHeadModel` model. If that it the case, the warnings you're getting is due to the incompatible layer names and modules. In addition, if you'd like to load an already trained checkpoint with `BertLMHeadModel` you would be required to write a weights converter or just use this model for creating the checkpoint.
Hope this answers your question :)
