### ISSUE TITLE
Any plan for releasing the checkpoints?

### ISSUE THREAD

**Issue by gaotianyu1350** [IntelLabs/academic-budget-bert#2]
Hi, thanks for the great work! I wonder if you have any plan regarding releasing your trained checkpoints? Thanks!

**Comment by peteriz** [comment]
Hi @gaotianyu1350, at this point we're not planning on releasing any model checkpoints. We included as much information and code as we can so that users will be able to reproduce the models we trained.
If you have any questions on reproduction feel free to ask

**Comment by gaotianyu1350** [comment]
Thanks!
