### ISSUE TITLE
How to combine wiki and bookcorpus into one file?

### ISSUE THREAD

**Issue by shizhediao** [IntelLabs/academic-budget-bert#20]
I found that in the dataset description, we can `Use process_data.py for pre-processing wikipedia/bookcorpus datasets into a single text file.`

What if I want to process these two datasets at the same time?
At which step should I combine them?
Thanks!

**Comment by peteriz** [comment]
Hi @shizhediao 
You can run `process_data.py` in parallel, one on wiki and another on bookcorpus.
You don't need to combine them, when running the sharding script (`shard_data.py`) you need to provide a path to a directory containing all corpus text files. The sharding process creates shards with samples from each dataset.

**Comment by shizhediao** [comment]
Thanks!
I found that the result of running process_data.py for wiki is like this figure. I was wondering is it useful for the wiki dir?
<img width="313" alt="image" src="https://user-images.githubusercontent.com/18120087/161980397-b34c3d0a-7308-4637-a86b-97713bce7618.png">

**Comment by peteriz** [comment]
You only need to provide the `*_one_article_per_line.txt` files in one directory for `shard_data.py`

**Comment by shizhediao** [comment]
OK, thanks!
