### ISSUE TITLE
Which kind of optimization you use from DeepSpeed

### ISSUE THREAD

**Issue by jzhang38** [IntelLabs/academic-budget-bert#29]
Hi,

First and foremost. Thank you for your excellent work.

Could you please elaborate more on what DeepSpeed functionality you used? Zero-1 or Zero-2 optimization, for example?

**Comment by peteriz** [comment]
Hi @jzhang38 
We used it as a training framework including its own fp16 training implementation. We did not use any Zero optimizations.
