### ISSUE TITLE
Which vocabulary file need to use?

### ISSUE THREAD

**Issue by NewDriverLee** [IntelLabs/academic-budget-bert#32]
Hi, I do the sample generation using the example command:
`python generate_samples.py \
    --dir <path_to_shards> \
    -o <output_path> \
    --dup_factor 10 \
    --seed 42 \
    --vocab_file <path_to_vocabulary_file> \
    --do_lower_case 1 \
    --masked_lm_prob 0.15 \ 
    --max_seq_length 128 \
    --model_name bert-large-uncased \
    --max_predictions_per_seq 20 \
    --n_processes 16`
 I found nothing is mentioned about the vocabulary file here or I missed something important. Do I need to download and use the vocabulary file in [https://huggingface.co/bert-large-uncased/blob/main/vocab.txt](url)?

**Comment by egsotic** [comment]
It's the vocab_file of the tokenizer, as used in: dataset/data/create_pretraining_data.py, BertTokenizer c'tor.
You can modify this by using BertTokenizer.from_pretrained(name_or_path), where name_or_path is a new param.
Note to add it to both generate_samples.py and create_pretraining_data.py

**Comment by NewDriverLee** [comment]
> It's the vocab_file of the tokenizer, as used in: dataset/data/create_pretraining_data.py, BertTokenizer c'tor. You can modify this by using BertTokenizer.from_pretrained(name_or_path), where name_or_path is a new param. Note to add it to both generate_samples.py and create_pretraining_data.py

Yes, I know it's the vocab_file of the tokenizer, which is used in the file create_pretraining_data.py for _BertTokenizer_. I mean this repository does not provide a vocab_file (or I missed). Do I need to use the vocabulary file provided by the Huggingface: [https://huggingface.co/bert-large-uncased/blob/main/vocab.txt](url)?

**Comment by NewDriverLee** [comment]
> Yes, for instance. You can also use your own with the mentioned modifications.

Thanks!
