### ISSUE TITLE
Question about validation and testing

### ISSUE THREAD

**Issue by peerdavid** [IntelLabs/academic-budget-bert#5]
Hello,

I wonder if there is a train-validation-test split or a train-test split only. I'm asking because during the dataset generation train-* and test-* files are generated, but no valid-* files. Then later, during pre-training, `distributed_pretraining_dataset.py` searches for valid-* files rather than test-* files (line 164). There are no such files and therefore, training crashes...

Thanks a lot!
David

**Comment by peteriz** [comment]
Hi @peerdavid, thanks for finding this issue. We only have train-valid sets (or train-test). 
I'll fix this (or you can go ahead and PR this😎 )
Thanks

**Comment by peerdavid** [comment]
Thanks a lot for your answer - sure I will open a PR :)

**Comment by Rotendahl** [comment]
@peerdavid I'm having the same problem. 
Let me know if you need a hand or tester.

**Comment by peerdavid** [comment]
> @peerdavid I'm having the same problem.
> Let me know if you need a hand or tester.

PR #7 should fix this issue - for me pre-training is no running on the bookcorpus + wiki dataset :)

**Comment by Rotendahl** [comment]
> > @peerdavid I'm having the same problem.
> 
> > Let me know if you need a hand or tester.
> 
> 
> 
> PR #7 should fix this issue - for me pre-training is no running on the bookcorpus + wiki dataset :)

Awesome!
I got pretraining running Yesterday without validation on the wiki dataset. Now I want to get it running with validation enabled and with the bookcorpus.

**Comment by peteriz** [comment]
> Thanks a lot for your answer - I will open a PR :)

Thanks!
