### ISSUE TITLE
Unable to train a roberta model?

### ISSUE THREAD

**Issue by dseddah** [IntelLabs/academic-budget-bert#8]
Hi everyone,
thanks for publishing your code :)
I've been trying to run your code on some data I had (just to see how it goes) and it seems that something is stalling right after the training has been initialized.

you can find the log here:
https://pastebin.com/Z2CrZA9C

when I ctrl+C the script,  things seemed to be stalling at a subprocess creation point in deepspeed (whether it's 10s or 30mn)

^CKilling subprocess 3401541
Killing subprocess 3401542
Main process received SIGINT, exiting
Traceback (most recent call last):
  File "/home/ROCQ/alpage/seddah/src/miniconda3/envs/budgetBERT/bin/deepspeed", line 6, in <module>
    main()
  File "/home/ROCQ/alpage/seddah/src/miniconda3/envs/budgetBERT/lib/python3.9/site-packages/deepspeed/launcher/runner.py", line 362, in main
    result.wait()
  File "/home/ROCQ/alpage/seddah/src/miniconda3/envs/budgetBERT/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/home/ROCQ/alpage/seddah/src/miniconda3/envs/budgetBERT/lib/python3.9/subprocess.py", line 1917, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/ROCQ/alpage/seddah/src/miniconda3/envs/budgetBERT/lib/python3.9/subprocess.py", line 1875, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

is there any chance you'd have an idea?

Best,
Djamé
ps: say hi to Omer :)

**Comment by dseddah** [comment]
So apparently, it's a bug from deepspeed (see https://github.com/huggingface/transformers/issues/12418 ). Some people were able to reproduce it and reduce to the following minimum working example

# test.py
import torch.distributed as dist
import argparse
import torch
parser = argparse.ArgumentParser()
parser.add_argument("--local_rank", type=int)
args = parser.parse_args()
torch.cuda.set_device(args.local_rank)
device = torch.device("cuda", args.local_rank)

dist.init_process_group("nccl")
dist.all_reduce(torch.ones(1).to(device), op=dist.ReduceOp.SUM)
(budgetBERT) seddah@serpentes2:~/src/miniconda3/envs/budgetBERT/academic-budget-bert/test$ cat test1.py
# test.py
import torch.distributed as dist
import argparse
import torch
parser = argparse.ArgumentParser()
parser.add_argument("--local_rank", type=int)
args = parser.parse_args()
torch.cuda.set_device(args.local_rank)
device = torch.device("cuda", args.local_rank)

dist.init_process_group("nccl")
dist.all_reduce(torch.ones(1).to(device), op=dist.ReduceOp.SUM)
---------------------

run with 
python -m torch.distributed.launch --nproc_per_node=2 test1.py --local_rank 1

and then press CTRL+C



python --version
Python 3.9.6
cuda 11.0

---------------
Name: deepspeed
Version: 0.4.3
Summary: DeepSpeed library
Home-page: http://deepspeed.ai
Author: DeepSpeed Team
Author-email: deepspeed@microsoft.com
License: MIT
Location: /home/ROCQ/alpage/seddah/src/miniconda3/envs/budgetBERT/lib/python3.9/site-packages
Requires: torch, packaging, psutil, ninja, tqdm, numpy, tensorboardX
Required-by

**Comment by stas00** [comment]
@dseddah, as you can see from the issue you linked to the minimal reproducible example has nothing to do with deepspeed directly. It's just plain pytorch. and your environment is probably a suspect. Are you running under a docker image?

In general such Issues like yours are very difficult to respond to since I have no idea what you're doing and how I could reproduce it.

**Comment by dseddah** [comment]
Hi @stas00, actually I reinstalled everything  and now the minimal working example is working (nor more hanging) but the deepspeed code is still stalling.
if you wanna try 
the package is here : 
http://pauillac.inria.fr/~seddah/4Thomas.tgz

everything should be easy to install (pip install -r req..)
and I've included a directory MissingDep and a script to install apex

inside there's a script run_me_thomas.sh to run the faulty code get_install_apex.sh

here you can find  the results of pip freeze  and conda env export  if you want to give it a try.

https://pastebin.com/fQUqFtyn

Djamé

**Comment by stas00** [comment]
Any chance you could set up the reproducible problem on google colab?

You can build upon my notebook here: https://github.com/stas00/porting/blob/master/transformers/deepspeed/DeepSpeed_on_colab_CLI.ipynb

**Comment by dseddah** [comment]
Good idea ! I'll try !

**Comment by stas00** [comment]
Meanwhile I tried to run your shared tarball - thanks for making an easy to run your bundle, but it crashes for me - this kind of crash usually means data or tokenizer are mismatched or some dimensions are off:

```
09/23/2021 15:21:47 - INFO - pretraining.dataset.pretraining_dataset -   ValidationDataset - shard 0 - length 1
0it [00:00, ?it/s]/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [98,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [99,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [100,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [101,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [102,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [103,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [104,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [105,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [106,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [107,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [108,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [109,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [110,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [111,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [112,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [113,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [114,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [115,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [116,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [117,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [118,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [119,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [120,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [121,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [122,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [123,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [162,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "run_pretraining.py", line 708, in <module>
    main()
  File "run_pretraining.py", line 700, in main
    start_training(args, model, optimizer, lr_scheduler, start_epoch)
  File "run_pretraining.py", line 512, in start_training
    eval_loss, scale_counter = train(
  File "run_pretraining.py", line 257, in train
    eval_loss = pretrain_validation(args, model, validation_dataset, global_step)
  File "run_pretraining.py", line 108, in pretrain_validation
    total_loss = model.forward(batch)
  File "/mnt/nvme1/code/huggingface/users/djame/4Thomas/academic-budget-bert/pretraining/base.py", line 80, in forward
    outputs = self.network(batch)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nvme1/code/github/00optimize/deepspeed/deepspeed/runtime/engine.py", line 1265, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nvme1/code/huggingface/users/djame/4Thomas/academic-budget-bert/pretraining/modeling.py", line 970, in forward
    bert_output = self.bert(
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nvme1/code/huggingface/users/djame/4Thomas/academic-budget-bert/pretraining/modeling.py", line 796, in forward
    encoder_output = self.encoder(
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nvme1/code/huggingface/users/djame/4Thomas/academic-budget-bert/pretraining/modeling.py", line 554, in forward
    layer_out = layer_module(
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nvme1/code/huggingface/users/djame/4Thomas/academic-budget-bert/pretraining/modeling.py", line 429, in forward
    self_attn_out = self.attention(pre_attn_input, attention_mask)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nvme1/code/huggingface/users/djame/4Thomas/academic-budget-bert/pretraining/modeling.py", line 362, in forward
    context_layer, attention_probs = self.self(input_tensor, attention_mask)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nvme1/code/huggingface/users/djame/4Thomas/academic-budget-bert/pretraining/modeling.py", line 314, in forward
    mixed_query_layer = self.query(hidden_states)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL error in: ../torch/lib/c10d/../c10d/NCCLUtils.hpp:158, unhandled cuda error, NCCL version 2.7.8
ncclUnhandledCudaError: Call to CUDA function failed.
```

**Comment by dseddah** [comment]
I know, I know. The data were tokenized with the French CamemBert vocabulary while the trainer is setup to the roberta's one. I just wanted to see if the code was working before changing the tokenizer in the code and everything. I'm glad to see that at least the code is working :) thanks again for your time !

**Comment by stas00** [comment]
This most likely has to do with your particular setup then. 

1. could you could run:
```
RUN_SLOW=1 pytest tests/deepspeed
```
and see if any of the tests fail for you - they shouldn't fail on a typical setup.

2. I also noticed you're using python - 3.9 - I think most of us are still on 3.8. So I'd test with py-38 first - it should be easy to quickly setup via conda. 

We probably should start testing with py39 as well. But let's see first what you get when you try the 2 suggestions above.

**Comment by peteriz** [comment]
@dseddah I hope our code works now. If you want to use a different tokenizer you can easily add/change existing tokenizers using in data generation/model. If apex is giving you trouble you replace the layer norms with vanilla pytorch layers, we didn't see much difference when using the latest pytorch and running on (quite) recent HW
